// src/components/RecommendationCard.tsx
"use client";

import Link from "next/link";
import { IRecommendation } from "@/types/recommendation";
import { getCategoryColor } from "@/lib/categories";

interface RecommendationCardProps {
  recommendation: IRecommendation;
  onDelete: (id: number) => void;
}

export default function RecommendationCard({
  recommendation,
  onDelete,
}: RecommendationCardProps) {
  return (
    <div
      className={`${getCategoryColor(recommendation.category)} rounded-2xl p-6 shadow-sm border border-neutral-200/20 hover:shadow-md transition-all duration-300`}>
      <div className="flex justify-between items-center mb-3">
        <span className="text-neutral-600 font-medium text-sm bg-neutral-100/50 px-3 py-1 rounded-full">
          {recommendation.category}
        </span>
        <span className="text-neutral-500 text-xs bg-neutral-50 px-2 py-1 rounded-lg">
          {recommendation.tag}
        </span>
      </div>

      <h3 className="font-medium text-lg mb-3 text-neutral-800">
        {recommendation.title}
      </h3>

      <p className="text-neutral-600 mb-4 line-clamp-2 leading-relaxed">
        {recommendation.description}
      </p>

      {recommendation.videoLink && (
        <div className="mb-4 rounded-xl overflow-hidden">
          <iframe
            src={recommendation.videoLink}
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
            className="w-full h-48"
          />
        </div>
      )}

      {recommendation.link && (
        <a
          href={recommendation.link}
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-600 hover:text-blue-800 block mb-3 underline decoration-blue-300 hover:decoration-blue-500 transition-all duration-200">
          Voir le lien
        </a>
      )}

      {recommendation.fileUrl && (
        <a
          href={recommendation.fileUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="text-green-600 hover:text-green-800 block mb-3 underline decoration-green-300 hover:decoration-green-500 transition-all duration-200">
          📎 {recommendation.fileName}
        </a>
      )}

      <div className="flex justify-between items-center pt-2">
        <Link
          href={`/recommendations/${recommendation.id}`}
          className="text-blue-600 hover:text-blue-800 font-medium transition-colors duration-200">
          Détails
        </Link>
        <button
          onClick={() => recommendation.id && onDelete(recommendation.id)}
          className="text-red-500 hover:text-red-700 text-sm transition-colors duration-200">
          Supprimer
        </button>
      </div>
    </div>
  );
}

// src/components/RecommendationCard.vue
<script setup lang="ts">
import { defineProps, defineEmits } from 'vue'
import type { IRecommendation } from '../types/recommendation'

const props = defineProps<{
  recommendation: IRecommendation
}>()

const emit = defineEmits<{
  (e: 'delete', recommendation: IRecommendation): void
  (e: 'click', recommendation: IRecommendation): void
}>()

const getCardColorByCategory = (category: string) => {
  // Implémentez la logique pour obtenir la couleur de la carte en fonction de la catégorie
  // Par exemple :
  const colors = {
    Movie: 'bg-blue-100',
    Book: 'bg-green-100',
    Music: 'bg-yellow-100',
    Podcast: 'bg-purple-100'
  }
  return colors[category] || 'bg-gray-100'
}

const hideButtonDeleteOnScroll = () => {
  // Implémentez la logique pour masquer le bouton de suppression lors du défilement
}
</script>

<template>
  <div
    @click="$emit('click', recommendation)"
    :class="getCardColorByCategory(recommendation.category)"
    class="gap-2 cursor-pointer h-full w-full border-1 rounded-xl inline-flex md:flex-col items-center p-4 md:p-6 md:m-2 border-black hover:shadow-lg transition duration-300 ease-in-out overflow-y-auto relative"
  >
    <div class="inline-flex md:w-full gap-2 items-center">
      <p class="text-gray-600">{{ recommendation.category }}</p>
      <p class="text-gray-500 text-sm border-2 hidden md:inline-flex rounded-lg p-1 bg-gray-50">
        {{ recommendation.tag }}
      </p>
    </div>
    <div class="w-full md:my-2">
      <h3 class="font-medium truncate text-lg">
        {{ recommendation.title }}
      </h3>
      <p class="text-gray-700 hidden md:inline-flex truncate">
        {{ recommendation.description }}
      </p>
    </div>
    <div v-if="recommendation.videoLink" class="w-full md:my-2">
      <iframe
        :src="recommendation.videoLink"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen
        class="w-full h-64 md:h-96"
      ></iframe>
    </div>
    <div class="w-full hidden md:inline-flex">
      <a
        :href="recommendation.link"
        target="_blank"
        class="text-gray-500 truncate hover:text-blue-400 cursor-pointer"
      >
        Link : {{ recommendation.link }}
      </a>
    </div>
    <div id="button-delete-recommendation" class="flex gap-2 mt-2 absolute right-2 top-0">
      <button
        class="bg-red-600 h-3 md:h-4 w-3 md:w-4 rounded-full cursor-pointer hover:bg-red-700"
        @click.stop="$emit('delete', recommendation)"
        type="button"
        @scroll="hideButtonDeleteOnScroll"
      ></button>
    </div>
  </div>
</template>
